server:
  port : 4049
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone : http://discUser:discPassword@localhost:4041/eureka/

#spring:
#  main:
#    allow-bean-definition-overriding: true
#  security:
#    oauth2:
#      opaquetoken:
#        introspection-uri: http://localhost:4030/auth/realms/plt_realm/protocol/openid-connect/token/introspect
#        client-id: plta_client_2!
#        client-secret: cKJG6AWkIPm5FAVHMVbt5OfgGbKalbJC
#
#      resourceserver:
#        jwt:
#          jwk-set-uri: http://localhost:4030/auth/realms/plt_realm/protocol/openid-connect/certs
spring:
#  data:
#    redis:
#      repositories:
#        enabled: true
  redis:
    host: localhost
    port: 6379
    password: 12345
  datasource:
    username: pltadict
    password : Ddfg$%^fghD
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/plta_dict_db?currentSchema=public
  jpa:
    show-sql: true
    generate-ddl: true
  main:
    allow-circular-references: true
  flyway:
    baseline-on-migrate: true
    enabled: true

#keycloak
keycloak:
  authServerUrl: ${OAUTH2_SERVER:http://10.25.72.75:4030}/auth
  realm: plt_realm
  resource: plt_client
  credentials:
    secret: 8R9DlO8EQjUcPzI8lwinQTpnmKhJEP0f
