server:
  port : 4052
eureka:
  instance:
    instance-id: user:${random.value}
    prefer-ip-address: true
  registryFetchIntervalSeconds: 5
  client:
    service-url:
      defaultZone: http://discUser:discPassword@localhost:4041/eureka/
spring:
  application:
    name: user-audit
  redis:
    host: localhost
    port: 6379
    password: 12345
  datasource:
    username: 'pltauseraudit'
    password: '!208fVDf^5VLTW'
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/plta_user_audit_db?currentSchema=public
  jpa:
    show-sql: true
    generate-ddl: false
  flyway:
    baseline-on-migrate: true
    enabled: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: admin
    password: admin123
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 1
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: package kz.platonus.pltauseraudit.config.mybatis.handler;
#keycloak
keycloak:
  authServerUrl: ${OAUTH2_SERVER:http://10.25.72.75:4030}/auth
  realm: plt_realm
  resource: plt_client
  credentials:
    secret: 8R9DlO8EQjUcPzI8lwinQTpnmKhJEP0f
resource-uuid: f7b1dbb5-56fe-48c5-92ac-d0f4b031d98b
kc:
  adapter:
    resource: admin-cli
    username: system@plta.kz
    password: system@plta.kz
app:
  gateway-url: http://10.25.72.24:4044/
  role:
    LISTENER_ID: 2
  queue:
    audit-send: q.audit-send

